name: CI

on: [push, pull_request]

{% if package_manager == 'Esy' -%}
{% raw -%}
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/checkout@v2
      - name: Cache esy dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: _export
          key: ${{ runner.OS }}-build-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install esy
        run: npm install -g esy@latest

      - name: Import dependencies
        if: steps.cache.outputs.cache-hit == 'true'
        run: esy import-build _export/*

      - name: Install dependencies
        run: esy install

      - name: Build
        run: esy build --release

      - name: Check formatting
        run: esy format

      - name: Run tests
        run: esy test
        
      - name: Export dependencies
        run: esy export-dependencies
{%- endraw %}
{% else -%}
{% raw -%}
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml-version: ['4.09.0', '4.08.1']
    steps:
      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - uses: actions/checkout@v2

      - name: Pin package
        run: opam pin add {% endraw %}{{ project_slug }}{% raw %}.dev -n .

      - name: Query and install external dependencies
        run: opam depext -yt {% endraw %}{{ project_slug }}{% raw %}

      - name: Install dependencies
        run: opam install -t . --deps-only

      - name: Build
        run: opam exec -- make

      - name: Check formatting
        run: opam exec -- make format

      - name: Run tests
        run: opam exec -- make test
{%- endraw -%}
{%- endif -%}
{%- raw %}

  test_bs:
    name: Build and test bucklescript
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache esy dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: test_bs/_export
          key: test_bs-${{ runner.OS }}-build-${{ hashFiles('test_bs/esy.lock/index.json') }}
          restore-keys: |
            test_bs-${{ runner.OS }}-build-${{ env.cache-name }}-
            test_bs-${{ runner.OS }}-build-
            test_bs-${{ runner.OS }}-

      - name: Install esy
        run: npm install -g esy@latest

      - name: Import dependencies
        if: steps.cache.outputs.cache-hit == 'true'
        run: esy import-build _export/*
        working-directory: ./test_bs

      - name: Install Esy dependencies
        run: esy install
        working-directory: ./test_bs

      - name: Build Esy
        run: esy build --release
        working-directory: ./test_bs

      - name: Install NPM dependencies
        run: yarn install
        working-directory: ./test_bs

      - name: Build
        run: yarn build
        working-directory: ./test_bs

      - name: Export dependencies
        run: esy export-dependencies
        working-directory: ./test_bs
{% endraw %}